language: c++
os: linux
dist: trusty
sudo: false
python: 3.6
notifications:
  email:
    recipients: sricher@ncsu.edu
    on_success: change
    on_failure: always

addons:
  apt:
  - python3
  - g++-5
  env:
  - CC=gcc-5
  - CXX=g++-5
  - F90=gfortran-5
